### ISSUE TITLE
Error When Using Version 2.0 

### ISSUE THREAD

**Issue by breezeBIT** [dacelib/dace#1]
Hi, I'm trying to learn dace so I downloaded the precompiled windows package and installed it at D:/DACE . My OS version is win7 sp1 64 bit and the IDE is  CodeLite V12.0.0.  TDM-GCC has already been installed on my computer, which includes gcc 5.1.0. When I tried to compile and run the very basic test titled "1. DA Basics" at tutorial 2, I met the following errors:

C:\Windows\system32\cmd.exe /C D:/TDM-GCC-32/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  "TEST_01.mk"  MakeIntermediateDirs && D:/TDM-GCC-32/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  "TEST_01.mk"  all
----------Building project:[ TEST_01 - Debug ]----------
D:/TDM-GCC-32/bin/g++.exe  -c  "E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp" -std=c++11 -g -O0 -Wall  -o ./Debug/main.cpp.o -ID:/DACE/include -I. -I.
D:/TDM-GCC-32/bin/g++.exe -o ./Debug/TEST_01 @"TEST_01.txt" -LD:/DACE/lib -L.  -ldace
./Debug/main.cpp.o: In function `main':
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:9: undefined reference to `DACE::DA::init(unsigned int, unsigned int)'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:10: undefined reference to `DACE::DA::DA(int, double)'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:11: undefined reference to `DACE::operator<<(std::ostream&, DACE::DA const&)'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:12: undefined reference to `DACE::sin(DACE::DA const&)'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:12: undefined reference to `DACE::operator<<(std::ostream&, DACE::DA const&)'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:12: undefined reference to `DACE::DA::~DA()'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:10: undefined reference to `DACE::DA::~DA()'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:12: undefined reference to `DACE::DA::~DA()'
E:/CodeLite_Workspace/DACE_TEST/TEST_01/main.cpp:10: undefined reference to `DACE::DA::~DA()'
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe: *** [Debug/TEST_01] Error 1
TEST_01.mk:78: recipe for target 'Debug/TEST_01' failed
====9 errors, 0 warnings====

It seems there are errors when linking to the compiled library and I don't know how to solve it. Please tell me what I should do to fix the problems. Thank you very much!

**Comment by mmassari1974** [comment]
Thank you for the feedback. Unfortunately the binary version for Windows is targeted at Visual Studio 2017, GCC have a different C++ name mangling convention. Therefore, you will not be able to link usiing the provided binary on Windows using GCC. Moreover, you are using CodelLite and if I remember right CodeLite ships a 32bit version of the GCC toolchain on Windows. The dace binaries are all 64bit.

If you want to use the dace on Windows with the GCC you should download the source and compile it yourself. The Build system is based on CMAKE which should have a generator for CodeLite. However, I'll suggest to move to a 64bit toolchain if possible, the 32bit limit on addressable memory will seriously limit the size of problems that can be addressed. Instead, if you want ot use the provided binary you should move to Visual Studio (the community edition can be freely downloaded form MS website.) or to Linux.

I'll update the release page adding all those information on the Windows Binary.

**Comment by breezeBIT** [comment]
Thank you for your help. I have changed my environment to Visual Studio 2017 and All things look to behave normally. However, when I run the example 6 titled "definite integral" at tutorial 1, I always get the wrong value 0. It seems that something goes wrong when evaluating the DA polynomial. To verify this, I write a simple example to compute sin(1.0) with the following code segment:
void test_06(void)
{
	DA::init(24, 1);
	
	DA x = DA(1);
	DA f = sin(x);
	double y = f.evalScalar(1.0);
	
	cout << "The result is: " << y << endl;
}
In my computer, the result of y is also zero. By the way, I have changed my OS to windows 10 64 bit and the precompiled version 2.0 package  is used with the static library dace.lib. I'm not sure if this is a bug, please help to check it. Many thanks!

**Comment by mmassari1974** [comment]
@breezeBIT in the future please open a new issue in case of different problem/error. 
dace.lib is not a static library, it is used by Visual Studio 2017 to correctly link the dace.dll. By chance (or maybe by design at MS) it has the same file extension of the static library (which is not included in the installer). Do not worry, you are linking against the correct library.

Regarding your example I'm not able to reproduce your error. I'm using Win10Pro 64 with VS2017 latest update. The following code compiles and give the expected results, can you please check the includes you are using are the same?

#include "stdafx.h"
#include <iostream>
#include <cmath>
#include <DA/dace.h>

using namespace std;
using namespace DACE;

int main()
{
	DA::init(24, 1);

	DA x = DA(1);
	DA f = sin(x);
	
	double y = f.evalScalar(1.0);

	cout << "expected resutls: " << sin(1.0) << endl;
	cout << "The result is: " << y << endl ;
	cout << "The error is: " << y - sin(1.0) << endl;

	return 0;
}

**Comment by breezeBIT** [comment]
Sorry for appending to the previous one and I will start a new issue next time. I just changed the configuration to Release x64 and  got the right value. In my previous operation, the Debug x64 configuration was used. I'm wondering why there are different behaviors between Debug and Release？

**Comment by mmassari1974** [comment]
The dace binaries are compiled in Release mode, but that should not affect the behavior of code compiled in debug mode. Thanks for the information, we will investigate the reason for this behavior.

**Comment by abgandar** [comment]
@breezeBIT can you please submit a new issue with this information so we can keep track of the Win64 Release/Debug issue separately? That way we can make sure it doesn't get lost.
