### ISSUE TITLE
Bug append operator

### ISSUE THREAD

**Issue by cloudstrife938** [dacelib/dace#31]
https://github.com/dacelib/dace/blob/d12a941d622a93fa9d36a7781d13d49651db54a5/interfaces/cxx/include/dace/AlgebraicVector_t.h#L266

This line of code appears to be incorrect, it should be changed to:     

const size_t size = obj.size();

Michele Maestrini

**Comment by mmassari1974** [comment]
Please, provide contextualization of the bug, why current implementation is wrong and in which way the proposed solution solve it. Thanks.

**Comment by cloudstrife938** [comment]
Current implementation stores in _size_ the size of the current object (_*this_). 
Afterwards, it uses this size to span the input _obj_ vector that needs to be appended. 

- If the size of the current and input objects are the same then it works. 
- If the size of the input object is shorter then this method tries to access _obj_ at an index that is out of bound.
- Finally, if the input _obj_ is longer than the current one, this method only appends a subset of the input _obj_ which is as long as the current object.

The proposed fix sets the variable _size_ to be as long as the input _obj_ that needs to be appended. This allows to span the entire _obj_ vector and append it to the current object regardless of the size of the input.
