### ISSUE TITLE
Error while reading `AlgebraicVector`s from text file

### ISSUE THREAD

**Issue by afossa** [dacelib/dace#33]
I am trying to write/read `AlgebraicVector<DA>` objects to/from text files, but the operator `>>` is failing to correctly load the vector from file, issuing the following error:

```
terminate called after throwing an instance of 'DACE::DACEException'
  what():  daceRead: Invalid data (ID: 632)
```

This seems to be caused by the blank line between the end of one vector component (i.e. `--------------`) and the beginning of the new one (i.e. `COEFFICIENTS ...`). (Manually) removing these blank lines fixes the issue.

I'll attach a minimum example in which the ouput file `test_vector_io.txt` is written using the `<<` operator, while `test_vector_io_no_blanks.txt` is the same file but without blank lines.

[test_vector_io.txt](https://github.com/dacelib/dace/files/8043355/test_vector_io.txt)
[test_vector_io_no_blanks.txt](https://github.com/dacelib/dace/files/8043356/test_vector_io_no_blanks.txt)
[testIO.txt](https://github.com/dacelib/dace/files/8043371/testIO.txt)

**Comment by mmassari1974** [comment]
Can you provide details on the platform on which this Is happening? Windows, Mac OS, Linux or all of them? Is this happening with the precompiled package or starting from source? In case you compile the DACE from source, which compiler(and version) did you use?

**Comment by afossa** [comment]
I have compiled DACE from source on two different PCs running Linux. In both cases I did a fresh clone of the `master` branch few days ago. The details of the platforms are the followings:

Arch Linux with Linux kernel 5.16.8
CMake 3.22.2
GCC 11.1.0

Ubuntu 18.04 with Linux kernel 5.4.0
CMake 3.22.2
GCC 7.5.0

It is also happening on a Windows PC (which is not mine) using a precompiled package.
