### ISSUE TITLE
Wrong output allocation in matrix/vector product

### ISSUE THREAD

**Issue by afossa** [dacelib/dace#45]
When computing the product between a (row) `AlgebraicVector` and an `AlgebraicMatrix` or an `AlgebraicMatrix` and a (column) `AlgebraicVector` the size allocated for the output vector is wrong, leading to unexpected results or errors if the matrix is not square.

The allocation occurs at lines 57 and 79 of `AlgebraicMatrix_t.h`.
* line 57: `obj1.size()` should be `obj2.ncols()`
* line 79: `obj2.size()` should be `obj1.nrows()`

**Comment by abgandar** [comment]
fixed by merge in commit #47
