### ISSUE TITLE
Possible relational operators?

### ISSUE THREAD

**Issue by zhutinglei** [dacelib/dace#48]
I read the `DA.h` file but did not find the definition of the relational operators (i.e. >, <, >=, <=, ==, !=).  I am trying to combine the `dacelib` with `boost::numeric::odeint`. The `odeint` package requires to implement `norm_inf` for the `state_type` aka `AlgebracVector<DA>` for my case. The `norm_inf` of  `AlgebracVector<DA>` should be the largest value in the vector.

Is this possible with `dacelib`？

**Comment by zhutinglei** [comment]
I misunderstood the dace lib and boost numeric odeint package. Problem solved.

**Comment by abgandar** [comment]
DA does not have a native concept of relational operators, as there is no common definition that works in an intuitive way as users may expect. Instead, users need to decide explicitly what they mean when they say polynomial A is bigger than polynomial B (e.g. by only comparing the constant part or bounding the range over a domain and comparing that).
We are working on a way to make DACE more compatible for use within boost (specifically odeint) in an upcoming release by including a suitable implementation of norm_inf for odeint.
